# Carta de demissão
print("nome da empresa")
Mycompany = input()
print("getor ou responsável no RH")
namegestor = input()
print("seu cargo atual na empresa")
cargoatual = input()
print("data de inicio do aviso previo")
datadeinicio = (input())
print("data do termino")
datadetermino = (input())
print("local e data")
localedata = input()
print("sua assinatura")
assinatura = input()
print("seu nome ocmpleto")
nomecompleto = input()

# impressão da carta
print(f"Á {Mycompany},")
print(f"Prezado(a) {namegestor}")
print(f"venho por meio desta carta comunicar formalmente meu pedido de demissão do cargo de {cargoatual}")
print(f"Estarei á disposição da empresa durante o aviso prévio, no período de {datadeinicio} a {datadetermino}")
print(f"{localedata}")
print(f"{assinatura}")
print(f"{nomecompleto}")